// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDojHkEtW_S0I-rYDZnfmXdmRNYWsad4NI',
    appId: '1:705108307688:web:fda302be3ab038d213e35d',
    messagingSenderId: '705108307688',
    projectId: 'peercircle-a4d39',
    authDomain: 'peercircle-a4d39.firebaseapp.com',
    storageBucket: 'peercircle-a4d39.firebasestorage.app',
    measurementId: 'G-13RRV36X6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX06FBB1xjc46vPrWFdi62dOMIJkRWIc4',
    appId: '1:705108307688:android:dc2bf9561e53f2e813e35d',
    messagingSenderId: '705108307688',
    projectId: 'peercircle-a4d39',
    storageBucket: 'peercircle-a4d39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgd035I6fexAZNQyiXs0b8DtYt67eeiVI',
    appId: '1:705108307688:ios:df4bfa8c762766ca13e35d',
    messagingSenderId: '705108307688',
    projectId: 'peercircle-a4d39',
    storageBucket: 'peercircle-a4d39.firebasestorage.app',
    iosBundleId: 'com.example.peerCircle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgd035I6fexAZNQyiXs0b8DtYt67eeiVI',
    appId: '1:705108307688:ios:df4bfa8c762766ca13e35d',
    messagingSenderId: '705108307688',
    projectId: 'peercircle-a4d39',
    storageBucket: 'peercircle-a4d39.firebasestorage.app',
    iosBundleId: 'com.example.peerCircle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDojHkEtW_S0I-rYDZnfmXdmRNYWsad4NI',
    appId: '1:705108307688:web:ab7b224da2de50dd13e35d',
    messagingSenderId: '705108307688',
    projectId: 'peercircle-a4d39',
    authDomain: 'peercircle-a4d39.firebaseapp.com',
    storageBucket: 'peercircle-a4d39.firebasestorage.app',
    measurementId: 'G-YH26Q8ZZB2',
  );
}
